from turtle import *

pensize(3)

penup()
goto(-120, 60)
pendown()
color("black")
begin_fill()


def horiz(length, quantity):
    for k in range(quantity):
        pendown()
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        left(60)
        forward(length)
        right(120)
        forward(length)
        left(60)
        forward(length)
        right(120)
        penup()


horiz(9, 6)
color('cyan')
end_fill()

hideturtle()
exitonclick()
